controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    velocity_controller:
      type: velocity_controllers/JointGroupVelocityController
    
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    ackermann_steering_controller:
      type: ackermann_steering_controller/AckermannSteeringController

velocity_controller:
  ros__parameters:
    joints:
      - wheel_right_back_joint
      - wheel_left_back_joint

ackermann_steering_controller:
  ros__parameters:
    traction_joints_names: ["wheel_right_back_joint", "wheel_left_back_joint"]
    steering_joints_names: ["right_front_steer_joint", "left_front_steer_joint"]
    wheelbase: 1.0
    traction_wheels_radius: 0.1
    traction_track_width: 0.5
    steering_track_width: 0.5
    publish_rate: 50.0
    base_frame_id: "base_link"
    open_loop: false
    position_feedback: false
    odom_frame_id: "odom"
    enable_odom_tf: true
    reference_timeout: 1.0